from .algorithm import KSubmodular, KGreedyTotalSizeConstrained, KGreedyIndividualSizeConstrained, KStochasticGreedyTotalSizeConstrained, KStochasticGreedyIndividualSizeConstrained

import independent_cascade